export const projects = [
  {
    id: "morpheus-env",
    title: "Morpheus Env",
    description: "Projeto acadêmico com o objetivo de utilizar práticas de segurança e implementação de ferramentas educacionais.",
    image: ["/images/projects/homemorpheus.png", "/images/projects/morpheus_conversor.png", "/images/projects/morpheus_moni.png"],
    icon: "bi bi-camera",
    stack: ["Django", "DRF", "IA Generativa"],
    full_stack: ['Python 3.12', 'Django 5.2', 'Django REST Framework', 'SQLite', 'TailwindCSS', 'OAuth2', 'GroqAI', 'Psutil', 'Swagger', 'Mkdocs'],
    functionalities: {
      "Monitoramento": "Análise em tempo real de CPU, RAM e Disco com visualização intuitiva.",
      "Análise por IA": "Utilização de IA generativa para interpretar dados do sistema e fornecer insights.",
      "Conversor Numérico": "Suporte completo para conversões entre binário, hexadecimal, octal e decimal.",
      "Operações Lógicas": "Execute operações AND, OR e XOR para trabalhar com valores booleanos.",
      "Autenticação Segura": "Sistema robusto com validação de email temporário e proteção avançada.",
      "Notificações": "Notificações por email com autenticação OAuth2 do Google integrada.",
    },
    github: "https://github.com/eukauacavalcante/morpheus_env",
    documentation: "https://eukauacavalcante.github.io/morpheus_env",
    fullDescription: "Morpheus Env é um simulador web que oferece ferramentas educacionais para análise de sistemas computacionais. O projeto foi desenvolvido com fins experimentais e acadêmicos, voltado à pesquisa, aprendizado e demonstração de conceitos.",
  },
  {
    id: "cars-project",
    title: "Revenda de Carros",
    description: "Plataforma de gestão de revendas de automóveis com sistema de administração interno e IA generativa.",
    image: ["/images/projects/cars_project.png"],
    icon: "bi bi-car-front",
    stack: ["Django", "IA Generativa"],
    full_stack: ["Django", "Groq AI", "SQLite", "TailwindCSS"],
    functionalities: {
      "Gestão de Veículos": "Cadastro, atualização e remoção de veículos com detalhes completos.",
      "Administração Interna": "Painel administrativo para gerenciar inventário, vendas e clientes.",
      "Geração de Descrições por IA": "Utilização de IA generativa para criar descrições detalhadas de veículos com informações incompletas.",
      "Interface Responsiva": "Design adaptável para uso em dispositivos móveis e desktops.",
      "Relatórios de Vendas": "Ferramentas para análise de desempenho e geração de relatórios detalhados.",
    },
    github: "https://github.com/eukauacavalcante/cars_project",
    documentation: null,
    fullDescription: "Software responsável pela gestão de revendas de veículos. Compatível com a integração de inteligência artificial para gerar descrições nos casos de informações ausentes.",
  },
  {
    id: "parking-service",
    title: "Serviço de Estacionamento",
    description: "Sistema RESTful completo de gestão de estacionamento com autenticação JWT e monitoramento em tempo real.",
    image: null,
    icon: "bi bi-p-circle",
    stack: ["Django", "DRF", "API"],
    full_stack: ["Django", "DRF", "SQLite", "JWT", "Swagger"],
    functionalities: {
      "Autenticação JWT": "Sistema seguro de registro e login utilizando JSON Web Tokens para proteção de endpoints.",
      "Gerenciamento de Vagas": "CRUD completo para vagas de estacionamento, permitindo adição, atualização, exclusão e listagem.",
      "Monitoramento em Tempo Real": "Acompanhamento ao vivo da ocupação das vagas de estacionamento.",
      "Documentação Interativa": "Documentação automática e interativa da API utilizando Swagger.",
    },
    github: "https://github.com/eukauacavalcante/parking_service",
    documentation: null,
    fullDescription: "Sistema RESTful completo de gestão de estacionamento com autenticação JWT, monitoramento em tempo real e documentação interativa.",
  },
  {
    id: "flix-api",
    title: "Flix API",
    description: "API para plataformas de streaming com autenticação robusta de usuários e gerenciamento eficiente de conteúdos.",
    image: null,
    icon: "bi bi-film",
    stack: ["Django", "DRF", "API"],
    full_stack: ["Django", "DRF", "SQLite", "JWT"],
    functionalities: {
      "Autenticação JWT": "Sistema seguro de registro e login utilizando JSON Web Tokens para proteção de endpoints.",
      "Gerenciamento de Conteúdos": "CRUD completo para filmes e séries, permitindo adição, atualização, exclusão e listagem.",
      "Categorias e Gêneros": "Organização eficiente de conteúdos por categorias e gêneros para melhor navegação.",
      "Avaliações e Comentários": "Funcionalidade para usuários avaliarem e comentarem sobre os conteúdos disponíveis.",
    },
    github: "https://github.com/eukauacavalcante/flix_api",
    documentation: null,
    fullDescription: "API para plataformas de streaming com autenticação robusta de usuários e gerenciamento eficiente de conteúdos.",
  },
];

export type Project = (typeof projects)[number];
